apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vestwise
  namespace: vestwise
spec:
  ingressClassName: nginx
  rules:
    - host: vestwise.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vestwise
                port:
                  number: 80
